# vim:ft=kitty

## name:     Catppuccin Kitty Frappe
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/frappe.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f1fffa
background              #272727
selection_foreground    #272727
selection_background    #f1fffa

# Cursor colors
cursor                  #f1fffa
cursor_text_color       #272727

# URL underline color when hovering with mouse
url_color               #ef8354

# The 16 terminal colors

# black
color0 #272727
color8 #272727

# red
color1 #ef8354
color9 #ef8354

# green
color2  #4cb944
color10 #4cb944

# yellow
color3  #ffb800
color11 #ffb800

# blue
color4  #5299d3
color12 #5299d3

# magenta
color5  #a167a5
color13 #a167a5

# cyan
#color6  #48acf0
#color14 #48acf0
color6  #00e0e0
color14 #00e0e0

# white
color7  #f1fffa
color15 #f1fffa

# font_family FiraCode Nerd Font
font_family JetBrainsMono Nerd Font Mono
# font_family Roboto Mono Nerd Font
font_size 16
