# vim:ft=kitty

## name:     Catppuccin Kitty Frappe
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/frappe.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #c0caf5
background              #24283b
selection_foreground    #24283b
selection_background    #c0caf5

# Cursor colors
cursor                  #c0caf5
cursor_text_color       #24283b

# URL underline color when hovering with mouse
url_color               #7aa2f7

# The 16 terminal colors

# black
color0 #24283b
color8 #24283b

# red
color1 #f7768e
color9 #f7768e

# green
color2  #9ece6a
color10 #9ece6a

# yellow
color3  #e0af68
color11 #e0af68

# blue
color4  #7aa2f7
color12 #7aa2f7

# magenta
color5  #bb9af7
color13 #bb9af7

# cyan
#color6  #48acf0
#color14 #48acf0
color6  #7dcfff
color14 #7dcfff

# white
color7  #c0caf5
color15 #c0caf5

# font_family FiraCode Nerd Font
font_family JetBrainsMono Nerd Font Mono
# font_family Roboto Mono Nerd Font
font_size 16

window_margin_width 12
