require("config.lualineConf")
require("config.nvimtreeConf")
require("config.telescopeConf")
require("config.nvimcmpConf")
require("config.leapConf")
require("config.conflict")
require("config.cinnamon")
